### ISSUE TITLE
smoothnes

### ISSUE THREAD

**Issue by rikardo1979** [dhrone/Raspdac-Display#10]
This is not really an issue but more like a polite request.
Is there a chance to make scrolling more smooth? Now it look like scrolling is done by rewriting in blocks and not single pixels? I mean like the whole display is divided to matrix of section for each character (8x8?) and whole this is rewritten in a time to create scrolling?
I am not sure, I just widely guessing here, so I do apologies in advance if I am totally wrong

**Comment by dhrone** [comment]
You are correct.  The animation is done by rewriting the sections of the display that are changing using characters.  That is the only way to update this style of display.  There is a feature of the display that does allow the display to scroll itself but it is only capable of scrolling the entire display, not individual lines.  Its also not particularly smoother than what my code is producing.

**Comment by rikardo1979** [comment]
Thanks for quick reply and your extended support on this. 
This is all I need to know. 
I am happy with it as it is now. It was just a thought. 
Please feel free to close this.

**Comment by dhrone** [comment]
I've moved the setting within the display code that attempts to smooth the display (by limiting the rate the display gets redrawn) into a start-up variable called ANIMATION_SMOOTHING.  Values between .15 to .25 seem good.  Marking this closed.
