### ISSUE TITLE
Set screen blank time when switching between artist and title

### ISSUE THREAD

**Issue by flagone** [dhrone/Raspdac-Display#11]
Issue 1

Hi Dhrone, as I posted on the Audiophonics forum, I think it would be good to be able to set a user defined period to blank the screen between the display of the artist and title information (I expect 0.5 or 1 second or so).  I expect it would work best if the scrolling stopped for a short period before the screen went  blank.  Perhaps that could be a user defined setting to go with the length of the screen blank.

Issue 2

I have adjusted your animation speed from .08 to .24.  Could this be a user defined option at the front of the script.

Issue 3

Is it possible for the script to have some display options other than artist and title.  Ones I have thought about are file type (flac, aac, mp3 etc) together with the bitrate and cpu temperature.  

Thanks again for your work on this script.

**Comment by dhrone** [comment]
Could you clarify issue 2?  Are you looking for this to be a configuration option that is outside the source code?  In other words, are you asking that I create a config file that I read at start-up?

**Comment by flagone** [comment]
No I think how you have set up the configuration at the top of the code is fine. It is just to have an option similar to scroll delay which you can set without going down into the code and editing it directly.

**Comment by dhrone** [comment]
I am almost done with a complete rewrite of the code that determines what to send to the display.  It uses a pages metaphor to allow what gets displayed to be much more easily modified.  This includes the ability to add a blank page in-between the transition from artist to title.  Testing and re-integration into the main branch of the code are next but good progress has been made.

**Comment by flagone** [comment]
Dhrone, thanks for your efforts.  I appreciate it.

**Comment by dhrone** [comment]
Progress has been made.  You may want to take a look at the current version in the working branch.  Not well tested but should be close to what you are looking for.

**Comment by flagone** [comment]
I will give it a go but probably won't be before the weekend due to work.

**Comment by flagone** [comment]
Got it working.  Thanks for your efforts.

Only difficulty was figuring out I had to run sudo pip install pylms

**Comment by flagone** [comment]
As a slight complication.  When listening to CDs they have a Artist, Album
and Title.  When listening to webradio there is no Album so it comes up
blank.  I tried taking the labels off (eg "Album:") but that isn't a
perfect solution as it is better to have the labels.

Not sure if the script can tell if there is no variable information in
which case it will skip the display?

**Comment by dhrone** [comment]
Actually, I just added that logic.  You can now set a page to hide when empty.  Pull the latest code that I literally just pushed.

**Comment by flagone** [comment]
Thanks, I will give it a go and report back.  Another issue was that when
displaying the bitrate it changes quickly from one number to another.  I
assume that is because of variable bitrate.  However, for display purposes,
I think just showing the current rate and sticking to it would be better
than changing a couple of times every second.

**Comment by dhrone** [comment]
I had to do something similar for the temperature and disk space variables.   I'm currently only updating those values once every 20 seconds.  Would a similar approach work for the bitrate problem?  What read frequency would you recommend?

**Comment by flagone** [comment]
How about 20 seconds or when the track changes whichever comes first.

**Comment by dhrone** [comment]
Ok.  I've made the coding changes.  It will now only read the bitrate value every 20 seconds unless a page change occurs in which case it immediately refreshes the value. I am not in a position to test the change right now but will load it later today. 

Update:  During testing I ran into some issues that I did not have time to resolve.  I'll try to get a proper fix down in the next few days.

**Comment by flagone** [comment]
When I try the latest script it starts then closes down and says goodbye.
Is that the issue you are resolving?

**Comment by dhrone** [comment]
The current version should work but perhaps I missed something.   Can I ask you to try a few things things?  First, make sure you are running the version that was committed on Sept 27th.  Second, run the software using the command line.  From the directory that contains the RaspdacDisplay.py file run...

sudo python RaspdacDisplay.py

When the code exits it should show the error message that is causing it to exit.  Send that error message to me.  Finally, you can revert to the last version that was published on Sept 25th.  This is the one with the commit message "Fixed change in alert change logic related to suppression".   FYI, when running the code from the command line, you may want to disable the OLED service.  You can do this by running the following commend.

sudo systemctl stop oled 

You can re-enable the service with...

sudo systemctl start oled

**Comment by flagone** [comment]
I tried the test script with no modifications and the latest one says
starting then goodbye and shuts down. I think there may be an error in it.

**Comment by flagone** [comment]
I got this message.  Hope it helps:

pi@moode:~ $ sudo python RaspDacDisplay.py
Traceback (most recent call last):
  File "RaspDacDisplay.py", line 841, in <module>
    prev_state = rd.status()
  File "RaspDacDisplay.py", line 685, in status
    self.avail = int(self.avail)
ValueError: invalid literal for int() with base 10: '208688  86'

**Comment by dhrone** [comment]
Yes, very useful.  Try the current version and see if it fixes the exception.  Can you let me know what distribution including version that you are using?  FYI, I'm still working the bitrate problem.  I'll likely get a fix posted for that later today or tomorrow.  Also chasing some bugs in the playlist position logic.

**Comment by dhrone** [comment]
Latest version posted hopefully resolves the bitrate and playlist position bugs.  Code also writes any unhandled exceptions to the log file now.  If you're code suddenly exists, you should check the end of your log file to determine what caused the exit.

**Comment by flagone** [comment]
Thanks, this one is working.

A couple of things that look like bugs:
- I can't get type (eg AAC / Flac etc) to display at all;
- the bottom line doesn't fit on the screen if there is a few items in the
  playlist.

**Comment by dhrone** [comment]
Try the latest commit to fix the first issue.  MPD doesn't really provide type data but it does provide the sample rate, bits / sample, and channel count.  I've used this to fill the type field.  FYI, SPOP (the Spotify daemon) does not provide any type information that I've been able to find.

The second is really a preference.  The display is only 16 characters wide.  If the current song position is greater than 9 and the tracklist length is greater than 9, at least 6 characters are going to be used to display track position and track length.

'10/12 '

Song time and duration takes a total of 11 characters

'00:03/4:43'

So, we are at least one character over what's needed.  Options include:
- Display everything and live with the line getting cropped (current setting)
- Display everything and scroll
- Remove at least one of the variables being displayed

All of that is configurable by modifying the PAGES_Play variable.  I've added a new file called "Pages Examples.py" that provides two different PAGES_Play examples.  The first is a version that shows the playlist position at the bottom of each page but truncates when the line is too long.  The second doesn't show the playlist data on each page but has a dedicated page that shows the playlist information periodically.

**Comment by flagone** [comment]
How about another option, instead of showing the current time in a track and then how long the track is, just do a countdown of the time in the track. So if it was 5 minutes long it would start at 5:00 and go down to 0:00.  That would save a lot of characters on the bottom part of the screen. 

Otherwise, I think it is really good.

**Comment by flagone** [comment]
If you look to implement a track count down option to save space on the
bottom line, it may have to default to count up if playing web radio as it
doesn't have a fixed track length.

**Comment by dhrone** [comment]
Just made the change but can not test until this evening.  You now have a new variable named "remaining" that contains a formatted version of the time remaining in the current song (e.g. ##:##).  If playing content with no duration (e.g. streaming content), it switches to a count-up timer.  To use it, replace the content of all of the bottom lines to reference it instead of position.  Example:
'''
          {
            'name':"bottom",
            'variables': [ "playlist_display", "position" ],
            'format':"{0} {1}",
            'justification':"left",
            'scroll':False
          }
'''
Should be changed to
'''
          {
            'name':"bottom",
            'variables': [ "playlist_display", "remaining" ],
            'format':"{0} {1}",
            'justification':"left",
            'scroll':False
          }
'''
This needs to be done for every page within PAGES_Playing.

**Comment by flagone** [comment]
Hi Dhrone, I like the latest changes.

It works great with streaming.  However, when playing AAC files I get the
following error.

2016-10-08 22:21:10,692:INFO:Raspdac display shutting down
2016-10-08 22:21:13,698:ERROR:Uncaught exception
Traceback (most recent call last):
  File "/home/pi/RaspDacDisplay.py", line 968, in <module>
    cstatus = rd.status()
  File "/home/pi/RaspDacDisplay.py", line 710, in status
    status = self.status_mpd()
  File "/home/pi/RaspDacDisplay.py", line 541, in status_mpd
    remaining = time.strftime("%M:%S", time.gmtime(int(duration - current)))
TypeError: unsupported operand type(s) for -: 'unicode' and 'unicode'

I hope this is helpful and you are able to fix it.

**Comment by dhrone** [comment]
Made a quick fix that I am not in a position to test.  If you get a chance pull the current version within the working branch and try again.

**Comment by flagone** [comment]
That seemed to fix it.  It is working fine now.

**Comment by dhrone** [comment]
Ok.  I think the set of issues that was raised at the top of this thread have been successfully resolved so I am closing this issue.  Please open up new issues as needed.  Thanks!
