### ISSUE TITLE
v0.7.0.2 only shows ready page, not the playing page

### ISSUE THREAD

**Issue by flagone** [dhrone/Raspdac-Display#12]
Hi dhrone

I have been happily using v0.7 and thought I would update to v0.7.0.2.  

However the new version only shows the PAGES_Stop page and will never go to the PAGES_Playing page.  I have checked the log and there is nothing suspicious.  Any ideas?

I even tried just using your standard RaspDacDisplay.py and pages.py without any modification and it does the same thing.  

Do I need to update anything other than those 2 files?

**Comment by dhrone** [comment]
I suspect your music sources are not set up correctly.  Check the variables at the top of RaspDacDisplay.py program.  You'll want to check the MPD_ENABLED, SPOP_ENABLED, etc. to see if they are set appropriate for your distribution.  Which distro are you using?

**Comment by flagone** [comment]
Hi dhrone

Now I have read your code, I believe I see the issue.  I will enable MPD_ENABLED and SPOP_ENABLED and check whether that fixes it.  I suspect it will.

As I am using Moode I assume I also make RUNE_ENABLED false.

**Comment by dhrone** [comment]
Yes, you should definitely disable Rune.  It is only relevant if you are using the Rune distro.

**Comment by flagone** [comment]
I enabled MPD and it now works.  I didn't enable SPOP as the logfile indicated it isn't present in Moode.

**Comment by flagone** [comment]
The log did mention redis was not found. As that appears to be for Runeaudio is that part of the problem?

**Comment by flagone** [comment]
I'm using Moode. The version prior to splitting out pages.py worked fine. Happy to make changes to get this new version to work. I think it was a good idea to split out pages.py as it saves setting them up each time raspdacdisplay.py changes.

**Comment by flagone** [comment]
I am happy this wasn't an issue and is resolved.
