### ISSUE TITLE
Date is not displaying correctly

### ISSUE THREAD

**Issue by flagone** [dhrone/Raspdac-Display#13]
Whilst my Raspberry Pi reports the date as 26 October when I ssh into it, on the ready display page it says it is Wed Oct 10. I think this page may be pulling the date incorrectly.

**Comment by dhrone** [comment]
There's a typo on in pages.py.  Look at the strftime setting in PAGES_Stop.  It shows up twice.  It's set to "%a %b %-m %H:%M" but it should be set to "%a %b %-d %H:%M".  Notice the change from -m (month) to -d (day).  That should fix the problem.  I'll update the version included in the repository but you can just make the change and then restart your system to fix it.

**Comment by flagone** [comment]
Hi dhrone, I made the change and it is now fixed.
