### ISSUE TITLE
Displayed date is not valid

### ISSUE THREAD

**Issue by erdoukki** [dhrone/Raspdac-Display#15]
With Timezone "CET-1CEST,M3.5.0,M10.5.0/3"
tc@piCorePlayer:~$ date
Sat Nov 19 07:30:18 CET 2016
but page.py display Sat Nov 11 ...
time is valid.

**Comment by dhrone** [comment]
Check the strftime setting for PAGES_Stop.   It's likely set to "%a %b %-m %H:%M".  It should be set to "%a %b %-d %H:%M".

**Comment by dhrone** [comment]
Assuming that the strftime typo was the problem.  If not, please re-open the issue.
