### ISSUE TITLE
Missing instructions for RuneAudio setup

### ISSUE THREAD

**Issue by arnome** [dhrone/Raspdac-Display#16]
Hi,
(it's not really an issue) first thank's for your great work on RaspDac Display. I follow your instructions for runeaudio and it appears that in my configuration : 
```
RuneOs: 0.3-beta
RuneUI: 1.3-beta
```
 two steps missing : 
- install the redis python 2.7 package : 
`> pip2 install redis`
- copy the pages.py module in the same directory of RaspDacDisplay.py : 
```
> cd /var/www/Raspdac-Display/
> cp pages.py /usr/local/bin
```
cheers,
arnome

**Comment by dhrone** [comment]
Should be resolved in the current instructions now.  Thanks for posting the issue.

**Comment by arnome** [comment]
You're welcome,
arnome
