### ISSUE TITLE
Latest scripts not running on MoodeAudio

### ISSUE THREAD

**Issue by rikardo1979** [dhrone/Raspdac-Display#18]
I am not sure what I doing wrong or where the problem may be but can not make these scripts running.
I have downloaded, did all the necessary but I have just blank display.
When I put the old ones back all is fine

**Comment by dhrone** [comment]
Just pulled the latest MoodeAudio image, pulled the current Raspdac-Display image, installed the required libraries, set the pin numbers in Winstar_GraphicOLED.py and fired it up with no problems.  Are you sure that you have your pins set correctly?

Rough description of installation
----------------------------------------
download and burn MoodeAudio to sd card
Boot Pi, associate to moodeaudio SSID
browse to http://moodeaudio.local
Go to network config page and place it on my local wireless network.  Reboot.
ssh pi@moodeaudio.local

  NOTE:  For some reason the system did not autoassign a DNS resolver.  So you may need to use resolvconf to add an appropriate nameserver.  I used 8.8.8.8

git clone https://github.com/dhrone/Raspdac-Display
cd Raspdac-Display
sudo apt-get update
sudo apt-get install python-pip
sudo pip install moment pylms python-mpd2
sudo vi  Winstar_GraphicOLED.py
  EDIT pin assignments for your system.
sudo python Raspdac-Display.py

**Comment by rikardo1979** [comment]
Thanks for reply here. I was trying few times but could not find where the issue is. 
Trouble is this was on existing system and not fresh install. The old scripts works fine so I think I have messed somewhere somehow.
I would need to start from scratch. Will try to flash new img on spare card and do it all again
