### ISSUE TITLE
RaspDac v3 Gen 2 needs other Pin Mappings

### ISSUE THREAD

**Issue by max2play** [dhrone/Raspdac-Display#19]
Hi,

the Gen 2 of RaspDac V3 seems to have other connections for the Display. Any Idea what needs to be changed in the pin mapping according to the pictures on the page?
http://www.audiophonics.fr/fr/dac-diy/audiophonics-i-sabre-dac-es9023-v3-tcxo-raspberry-pi-20-a-b-i2s-p-10657.html 

Cheers,
Stefan

**Comment by dhrone** [comment]
For the display, the only thing that has changed is the headers.  Gen 1 had a single header that was intended to be connected to the single header on the display.  Gen 2 has three headers.  Two six pin headers and one three pin header.  For Gen 2, the first six pin header is hooked up to pins 1-6 of the display and the second six pin headers is connected to pins 11-16 of the display, leaving pins 7-10 of the display disconnected.  The actual GPIO assignments have not changed.  The remaining three pin headers is there to support an optional IR sensor.
