### ISSUE TITLE
Display not working

### ISSUE THREAD

**Issue by fferroni** [dhrone/Raspdac-Display#20]
Hi,

I downloaded the system and tested on a Volumio 2 RPi3, with an Audiophonics Sabre V3 DAC with wiring to the OLED screen like such [http://imgur.com/a/aLcB5](http://imgur.com/a/aLcB5) but even though the oled.service is active, I do not see anything on the screen when I am playing music... Ideas?

P.S. In the README instructions, there are a few steps missing when copying files over to /usr/local/bin, but I guess anyone with minimal Linux knowledge can understand :)

**Comment by dhrone** [comment]
Do you have the gen 1 or the gen 2 V3 DAC?  The gen 2 requires that pins 11-16 be reversed.  See the description on http://www.audiophonics.fr/en/diy-dac/audiophonics-i-sabre-dac-es9023-v2-tcxo-raspberry-pi-20-a-b-i2s-p-10657.html.

Would be great to get any updates into the README.  Can you share what was missing?

**Comment by fferroni** [comment]
I have the generation 2, so I reversed the pins as shown here like this [picture](http://audiophonics.fr/img/cms/Usabre%20v3%20avec%20raspeberry%20Pi%202.jpg). However, it doesn't work... I run the Winstar_GraphicOLED.py test file, but I see nothing on the screen. The sds.service works perfectly, just not the LCD. :(

**Comment by fferroni** [comment]
Great, it works! 👍
