### ISSUE TITLE
Mistake in instruction

### ISSUE THREAD

**Issue by rikardo1979** [dhrone/Raspdac-Display#5]
you have a little mistake in your instruction.
In section for RuneAudio 
**A. Files for the display**
`cp Winstar_GraphicOLD.py /usr/local/bin/` 
and it should be 
`cp Winstar_GraphicOLED.py /usr/local/bin/`

Other than this brilliant work 

Thank you very much ;)

**Comment by dhrone** [comment]
Thanks for the correction.  I've made the change.
