### ISSUE TITLE
Wrong timezone

### ISSUE THREAD

**Issue by rikardo1979** [dhrone/Raspdac-Display#6]
Not sure where the issue is or if this is an issue actually :)
If I want the right time to be displayed I have to set 

```
TIMEZONE="GMT+1"
Paris.  TIMEZONE = "Europe/London"

But we are actually GMT+0. But if I leave it its one hour behind...
Maybe wrong time server?
```

**Comment by dhrone** [comment]
I'm on travel right now without access to my Pi3/OLED setup so it may be awhile before I can look into the this.  A few items to confirm though.  
- Please verify that the system clock is appropriately set, preferrably from a valid NTP source.  
- Check to see if this might be a daylight savings time issue
- Can you confirm what the TIMEZONE variable is set to when the problem is occurring?
  FYI, I think you can use "timedatectl status" to get a breakout of the local and system times.

**Comment by rikardo1979** [comment]
@dhrone thanks for helping again 

here is output of the timedatectl status 

```
[root@runeaudio ~]# timedatectl status
      Local time: Tue 2016-04-26 16:37:45 BST
  Universal time: Tue 2016-04-26 15:37:45 UTC
        RTC time: n/a
       Time zone: Europe/London (BST, +0100)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no

```

**Comment by rikardo1979** [comment]
if I use GMT+0 as it should be that it looks like 

```
[root@runeaudio ~]# timedatectl status
      Local time: Tue 2016-04-26 16:18:51 UTC
  Universal time: Tue 2016-04-26 16:18:51 UTC
        RTC time: n/a
       Time zone: UTC (UTC, +0000)
 Network time on: yes
NTP synchronized: no
 RTC in local TZ: no
```

Which is wrong as it is 1 hour behind

**Comment by dhrone** [comment]
I'm not sure what the error is.  Isn't London +1 ahead of GMT during the summer?

**Comment by rikardo1979** [comment]
London/Time zones/Greenwich Mean Time Zone
Greenwich Mean Time Zone
UTC+00:00

So if I have selected London and NTP is right than my time should be right, or?

**Comment by dhrone** [comment]
Yes, you should select Europe/London.  FYI, Europe/London is not the same as GMT during the summer.

Also note that RaspdacDisplay.py does not use the local setting to determine what time zone the system is in.  You need to specifically set the TIMEZONE variable to "Europe/London".  This is currently at line 35 of the file.

**Comment by rikardo1979** [comment]
/usr/local/bin/RaspDacDisplay.py

```
# Adjust this setting to localize the time display to your region
TIMEZONE="GMT+0"
TIME24HOUR=True
#TIMEZONE="Europe/London"
```

**Comment by dhrone** [comment]
Did you get this resolved?  FYI, from my understanding of your situation, your config you look like...

```
# Adjust this setting to localize the time display to your region
#TIMEZONE="GMT+0"
TIME24HOUR=True
TIMEZONE="Europe/London"
```

**Comment by rikardo1979** [comment]
if I have it like this the time is wrong, one hour behind
I have to set it to GMT+1 to get the right time

**Comment by dhrone** [comment]
I'm not sure what is going wrong on your system.  I just adjusted mine to TIMEZONE="Europe/London" and restarted.  It is now displaying the time as 3:22pm, which google confirms as the current time in London.  For reference, here is the current output from timedatectl status.

```
[root@runeaudio dhrone]# timedatectl status
      Local time: Fri 2016-04-29 16:22:11 CEST
  Universal time: Fri 2016-04-29 14:22:11 UTC
        RTC time: n/a
       Time zone: Europe/Berlin (CEST, +0200)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
```

**Comment by rikardo1979** [comment]
OK, I really need to apologies here...It was my fault as I have had two TIMEZONE lines in the script and the one with Europe/London was commented ...
Sorry

All good now so we can close this
