### ISSUE TITLE
Dist-Upgrade breaks mpd

### ISSUE THREAD

**Issue by gsejourne** [dhrone/Raspdac-Display#7]
Hi,

I've followed your README instructions, and they used to work well.
However, more recently, doing the `paceman -Syu` to upgrade the distro breaks all sorts of 'in-house' Runeaudio package (like mpd -> mad-rune, etc), due to missing libraries, like libicui, etc.

Following the exact same steps without doing the upgrade seem to work however. Don't know if if brings other downsides, like python2 vs 3, etc. as I've tweaked it already.

**Comment by dhrone** [comment]
Did you allow pacman to update the packages, or just run the command and then say no when it asks you for permission to proceed?  When you just run the program, it updates it package lists but does not actually make any other changes to the system.  When I allowed the command to update all of the installed packages, it did break the distribution.

**Comment by gsejourne** [comment]
Yes I did run the upgrade, and said Yes.

**Comment by gsejourne** [comment]
Arghhh,
I just realized you mention I recommend that you NOT proceed with the
installation
in the steps...
Didn't read that far, so my bad I guess.
Guess you can close this then, sorry.

And great job by the way !
I'd been willing to rewrite the py script that's shipped by Audiophonics to
handle the OLED screen using the mpd API, but you've done such a great job,
I don't have to :)

Cheers,

-Guillaume

2016-04-26 20:24 GMT+02:00 guillaume SEJOURNE guillaume.sejourne@gmail.com
:

> Yes I did run the upgrade, and said Yes.
> Le 26 avr. 2016 8:22 PM, "dhrone" notifications@github.com a écrit :
> 
> > Did you allow pacman to update the packages, or just run the command and
> > then say no when it asks you for permission to proceed? When you just run
> > the program, it updates it package lists but does not actually make any
> > other changes to the system. When I allowed the command to update all of
> > the installed packages, it did break the distribution.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/dhrone/Raspdac-Display/issues/7#issuecomment-214837816

## 

= = = = =============== = = = =
Guillaume Séjourné
guillaume.sejourne@gmail.com
= = = = =============== = = = =

**Comment by dhrone** [comment]
Thanks.  I'm going to leave this open until I change the instructions to make that step more clear.  Now that both of us have experienced stability problems with the update, I want to make that a requirement and not a recommendation.

**Comment by dhrone** [comment]
Updated instructions so closing this issue.
