### ISSUE TITLE
MPDClient and use_unicode

### ISSUE THREAD

**Issue by sandradabo** [dhrone/Raspdac-Display#8]
Hello,

I am trying to run your scripts on Volumio 2 RC1 and it fails with following error:

volumio@volumio:~$ sudo python ./RaspDacDisplay.py
Traceback (most recent call last):
  File "./RaspDacDisplay.py", line 298, in <module>
    rd = RaspDac_Display()
  File "./RaspDacDisplay.py", line 63, in **init**
    self.client = MPDClient(use_unicode=True)
TypeError: **init**() got an unexpected keyword argument 'use_unicode'

So when I remove this argument it works. Am I missing something on my system and can this work properly without this flag ?

Thank you

**Comment by dhrone** [comment]
You've probably got python-mpd installed instead of python-mpd2.  I'm using the later version specifically because of it's Unicode support.  See https://pypi.python.org/pypi/python-mpd2/0.5.1 for a description of the correct version.

**Comment by dhrone** [comment]
Closing this issue
